name: Dependabot Auto-Merge

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This step will run any tests that are configured in the repository
      # Since the repository is minimal, we're adding a placeholder for tests
      # You should customize this step based on your actual test setup
      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here, for example:
          # npm test
          # or
          # python -m pytest
          # or any other test command appropriate for your project
          
          # For now, we'll use a simple exit 0 to simulate passing tests
          exit 0

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}